# typed: false
# frozen_string_literal: true

# This file is generated by scripts/update-formula.sh — do not edit by hand.
# The sha256 values below come from a cosign-verified checksums file.
class Meerkat < Formula
  desc "Knowledge base as a static binary, served over CLI, MCP, and HTTP"
  homepage "https://github.com/zegit-zoo/meerkat"
  license "Apache-2.0"
  # No explicit `version`: Homebrew scans 0.11.1-style versions out of the
  # release URLs below, and `brew audit --strict` rejects restating it.

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/zegit-zoo/meerkat/releases/download/v0.11.1/meerkat_0.11.1_darwin_arm64.tar.gz"
      sha256 "82a8ad9cf39782b8c6ba381ac865324a42b31e9f1cd6796fc748afd2099164cb"
    end

    on_intel do
      url "https://github.com/zegit-zoo/meerkat/releases/download/v0.11.1/meerkat_0.11.1_darwin_amd64.tar.gz"
      sha256 "18e56e34064bbec522e222abc43c9b87312bc4c81e257e938756cc92f6315f5b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/zegit-zoo/meerkat/releases/download/v0.11.1/meerkat_0.11.1_linux_arm64.tar.gz"
      sha256 "b3f48ff1781b75f2927846e101aa397c356a519adfb7f1e95b2b22d64e074957"
    end

    on_intel do
      url "https://github.com/zegit-zoo/meerkat/releases/download/v0.11.1/meerkat_0.11.1_linux_amd64.tar.gz"
      sha256 "6ad0fecd7c09269ad0eb06fddea745418f1cac0a8e6ad00b2f624bdd458f5164"
    end
  end

  conflicts_with "mk", because: "both install a `mk` executable"

  def install
    bin.install "meerkat"
    bin.install_symlink "meerkat" => "mk"
    doc.install "README.md", "LICENSE", "NOTICE", "THIRD-PARTY-LICENSES.txt"
    # Default shells (bash, zsh, fish); `meerkat completion <shell>` is a
    # cobra subcommand, which is the default :none parameter format.
    generate_completions_from_executable(bin/"meerkat", "completion")
  end

  def caveats
    <<~EOS
      `mk` is installed as a symlink to `meerkat`; the two are interchangeable.
      It conflicts with the `mk` formula (the Plan 9 build tool), which ships an
      unrelated `mk` executable.

      Update this install with:
        brew upgrade meerkat

      Do not use the built-in `mk update` self-updater on a Homebrew install: it
      swaps the binary in place, inside the Cellar, leaving Homebrew's records
      pointing at a file it no longer knows the checksum of. `brew upgrade` is
      the supported path.

      meerkat checks for new releases in the background and prints a one-line
      notice. To silence it:
        export MEERKAT_NO_UPDATE_CHECK=1
    EOS
  end

  test do
    ENV["MEERKAT_NO_UPDATE_CHECK"] = "1"

    assert_match version.to_s, shell_output("#{bin}/meerkat version")
    assert_match "knowledge-base", shell_output("#{bin}/mk --help")
  end
end
