# typed: false
# frozen_string_literal: true

# This file is generated by scripts/update-formula.sh — do not edit by hand.
# The sha256 values below come from a cosign-verified checksums file.
class Meerkat < Formula
  desc "Knowledge base as a static binary, served over CLI, MCP, and HTTP"
  homepage "https://github.com/zegit-zoo/meerkat"
  license "Apache-2.0"
  # No explicit `version`: Homebrew scans 0.11.1-style versions out of the
  # release URLs below, and `brew audit --strict` rejects restating it.

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/zegit-zoo/meerkat/releases/download/v0.12.0/meerkat_0.12.0_darwin_arm64.tar.gz"
      sha256 "671014d3c0b78225a071497e0f46b2768e6ec6eb48853a765f87cf3aa172362d"
    end

    on_intel do
      url "https://github.com/zegit-zoo/meerkat/releases/download/v0.12.0/meerkat_0.12.0_darwin_amd64.tar.gz"
      sha256 "25655ee8314cf79e1d1c6379bde376ee6f37bb55ed6b89d3f37277f9044c89c1"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/zegit-zoo/meerkat/releases/download/v0.12.0/meerkat_0.12.0_linux_arm64.tar.gz"
      sha256 "b4099e511e2f2c247102caf3a12d14ae85aa7fba1d4652c4f3982e5f3d1b3fa3"
    end

    on_intel do
      url "https://github.com/zegit-zoo/meerkat/releases/download/v0.12.0/meerkat_0.12.0_linux_amd64.tar.gz"
      sha256 "51f75acab5d1a8f5bf62fbd9a0ce9921f8f6019f397f861a9187d3541d8a7edc"
    end
  end

  conflicts_with "mk", because: "both install a `mk` executable"

  def install
    bin.install "meerkat"
    bin.install_symlink "meerkat" => "mk"
    doc.install "README.md", "LICENSE", "NOTICE", "THIRD-PARTY-LICENSES.txt"
    # Default shells (bash, zsh, fish); `meerkat completion <shell>` is a
    # cobra subcommand, which is the default :none parameter format.
    generate_completions_from_executable(bin/"meerkat", "completion")
  end

  def caveats
    <<~EOS
      `mk` is installed as a symlink to `meerkat`; the two are interchangeable.
      It conflicts with the `mk` formula (the Plan 9 build tool), which ships an
      unrelated `mk` executable.

      Use `brew upgrade meerkat` to update. The built-in `mk update`
      self-updater is not for Homebrew installs: releases after 0.11.1 refuse to
      run it from the Cellar, and 0.11.1 would swap the binary in place behind
      Homebrew's back.

      meerkat checks for new releases in the background and prints a one-line
      notice. To silence it:
        export MEERKAT_NO_UPDATE_CHECK=1
    EOS
  end

  test do
    ENV["MEERKAT_NO_UPDATE_CHECK"] = "1"

    assert_match version.to_s, shell_output("#{bin}/meerkat version")
    assert_match "knowledge-base", shell_output("#{bin}/mk --help")
  end
end
